typography_spectrum: 0.7295639908406883
color:
  brandStrength: 0.9775012694299221
  lightness: 0.4046529142651707
  saturation: 0.06924993149004877
  rhythmicContrast: 0.5875975666567683
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.48307253094390035
name: A Way Forward
navigation:
  - name: Twitter
    url: 'http://twitter.com/ashishjoy'
    type: external
  - name: Facebook
    url: 'http://facebook.com/ashishjoy'
    type: external
title: A Way Forward
description: online home of @ashishjoy
